language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script: mvn clean install --quiet -B
jdk:
    - openjdk8
branches:
    only:
        - master
notifications:
    email:
        - devacfr@mac.com
